name: MacRDP
on: 
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:                 
    - name: Enable VNC
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -clientopts -setvnclegacy -vnclegacy yes -setvncpw -vncpw "12345678" -restart -agent -privs -all

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
